# Generated by Django 3.2.23 on 2023-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_last_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='chain_count',
            field=models.IntegerField(default=0),
        ),
    ]
