# Generated by Django 3.2.23 on 2023-11-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_chain_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='last_completed_date',
        ),
    ]
