# Generated by Django 3.2.23 on 2023-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20231214_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='streak',
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
