# Generated by Django 3.2.23 on 2023-11-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_last_completed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='chain_count',
            new_name='streak',
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
